### ISSUE TITLE
IMAGES 

### ISSUE THREAD

**Issue by ShreyaDevagiri** [J-division-2020-2021-even/Repo-17#2]
![Screenshot 2021-06-15 142315](https://user-images.githubusercontent.com/83583862/122023835-88b99280-cde5-11eb-9fd6-946854ca0141.png)

**Comment by ShreyaDevagiri** [comment]
![WhatsApp Image 2021-06-15 at 12 23 41 PM](https://user-images.githubusercontent.com/83583862/122038362-25366180-cdf3-11eb-85ba-de5ed4a05246.jpeg)

**Comment by bharatjain2** [comment]
![image](https://user-images.githubusercontent.com/83595120/122168001-5b2e2100-ce99-11eb-8760-9a5e06231a88.png)

**Comment by ShreyaDevagiri** [comment]
![WhatsApp Image final](https://user-images.githubusercontent.com/83583862/122170407-27082f80-ce9c-11eb-8eae-52c9aaf39a09.jpeg)
