### ISSUE TITLE
pic

### ISSUE THREAD

**Issue by bharatjain2** [J-division-2020-2021-even/Repo-17#3]
![image](https://user-images.githubusercontent.com/83595120/122105345-4bc9bc00-ce36-11eb-95aa-6cb1947c99a9.png)

**Comment by ShreyaDevagiri** [comment]
![WhatsApp Image 2021-06-18 at 7 55 44 PM](https://user-images.githubusercontent.com/83583862/122582388-bf0d4100-d075-11eb-9560-5c93b1d4d519.jpeg)
![WhatsApp Image 2021-06-18 at 7 15 44 PM](https://user-images.githubusercontent.com/83583862/122582411-c46a8b80-d075-11eb-8a51-02ac1ac7da06.jpeg)
![WhatsApp Image 2021-06-18 at 6 24 23 PM](https://user-images.githubusercontent.com/83583862/122582417-c6cce580-d075-11eb-8576-623ac98156b8.jpeg)
![Screenshot 2021-06-15 135351 (2)](https://user-images.githubusercontent.com/83583862/122582446-cfbdb700-d075-11eb-8a22-89c45b50c480.png)
![Screenshot 2021-06-18 203822](https://user-images.githubusercontent.com/83583862/122582500-dc420f80-d075-11eb-9019-b0d67cf7a0de.png)

**Comment by ShreyaDevagiri** [comment]
![Screenshot 2021-06-18 203949](https://user-images.githubusercontent.com/83583862/122582582-ed8b1c00-d075-11eb-9817-b25ea92084ee.png)

**Comment by ShreyaDevagiri** [comment]
![WhatsApp Image 2021-06-18 at 8 46 16 PM](https://user-images.githubusercontent.com/83583862/122582914-52df0d00-d076-11eb-922a-f2530bc67a1d.jpeg)

**Comment by ShreyaDevagiri** [comment]
![Autodesk Inventor Professional 2022 02-07-2021 18_50_55](https://user-images.githubusercontent.com/83583862/124280892-d1ec3f00-db66-11eb-910e-6d8dbab5a8e6.png)
![Autodesk Inventor Professional 2022 02-07-2021 18_51_30](https://user-images.githubusercontent.com/83583862/124280907-d57fc600-db66-11eb-9180-ebf5ba3860ad.png)
![Autodesk Inventor Professional 2022 02-07-2021 18_52_25](https://user-images.githubusercontent.com/83583862/124280914-d7498980-db66-11eb-97e3-aaf501caa4ce.png)
